/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarPasswordRouteImport } from './routes/recuperar-password'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppCitasRouteImport } from './routes/app.citas'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppClientesIndexRouteImport } from './routes/app.clientes.index'
import { Route as AppClientesCustomerIdRouteImport } from './routes/app.clientes.$customerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarPasswordRoute = RecuperarPasswordRouteImport.update({
  id: '/recuperar-password',
  path: '/recuperar-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppCitasRoute = AppCitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppClientesCustomerIdRoute = AppClientesCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => AppClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/citas': typeof AppCitasRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/$customerId': typeof AppClientesCustomerIdRoute
  '/app/clientes/': typeof AppClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/citas': typeof AppCitasRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app': typeof AppIndexRoute
  '/app/clientes/$customerId': typeof AppClientesCustomerIdRoute
  '/app/clientes': typeof AppClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-password': typeof RecuperarPasswordRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/citas': typeof AppCitasRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/$customerId': typeof AppClientesCustomerIdRoute
  '/app/clientes/': typeof AppClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/recuperar-password'
    | '/app/agenda'
    | '/app/citas'
    | '/app/clientes'
    | '/app/dashboard'
    | '/app/'
    | '/app/clientes/$customerId'
    | '/app/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recuperar-password'
    | '/app/agenda'
    | '/app/citas'
    | '/app/dashboard'
    | '/app'
    | '/app/clientes/$customerId'
    | '/app/clientes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/recuperar-password'
    | '/app/agenda'
    | '/app/citas'
    | '/app/clientes'
    | '/app/dashboard'
    | '/app/'
    | '/app/clientes/$customerId'
    | '/app/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecuperarPasswordRoute: typeof RecuperarPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-password': {
      id: '/recuperar-password'
      path: '/recuperar-password'
      fullPath: '/recuperar-password'
      preLoaderRoute: typeof RecuperarPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/citas': {
      id: '/app/citas'
      path: '/citas'
      fullPath: '/app/citas'
      preLoaderRoute: typeof AppCitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/': {
      id: '/app/clientes/'
      path: '/'
      fullPath: '/app/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/app/clientes/$customerId': {
      id: '/app/clientes/$customerId'
      path: '/$customerId'
      fullPath: '/app/clientes/$customerId'
      preLoaderRoute: typeof AppClientesCustomerIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
  }
}

interface AppClientesRouteChildren {
  AppClientesCustomerIdRoute: typeof AppClientesCustomerIdRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesCustomerIdRoute: AppClientesCustomerIdRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppCitasRoute: typeof AppCitasRoute
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppCitasRoute: AppCitasRoute,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RecuperarPasswordRoute: RecuperarPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
